id: I1DDE7345
default_language: fr
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:52.455195
last_modified: 2023-01-04 11:32:52.455210
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  E59E:
    title: The Prayer in Six Vajra Lines
    base_file: E59E.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
